### ISSUE TITLE
Expand Fuzzy Search Sometimes Too Eager

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#103]
Windows 10, ST 3211, Emmet 2.1.16

I have an HTML document that contains a class of "trip-event-counselor".

I want to add another div with a class of "trip-event-url".

On an empty line with a few tabs for indentation, I enter `.trip-event-url`, then press the Tab key to expand this.  It changes the line to be only `.trip-event-counselor`.  It does not add a div around that, nor does it give me a popup to let me select which one I want.

I assume this is because the letters in `url` can be found in `counselor`.

If I prefix the class with `div`, for example: `div.trip-event-url`, it correctly expands to `<div class="trip-event-url"></div>`.

**Comment by sergeche** [comment]
Not sure where the problem is. Can you record a small video that displays what’s happening?
If you already have entered abbreviation in document somehow, make sure you’ve captured it first as described here: https://github.com/emmetio/sublime-text-plugin#expanding-abbreviation
When captured, you may add more elements to abbreviation

**Comment by michaelalandawson** [comment]
I believe this issue is resolved related to the CFML issue [101](https://github.com/emmetio/sublime-text-plugin/issues/101).  I did not have the abbreviation captured.

Adding `"text.html.cfml - meta.tag"` to `abbreviation_scopes` resolved this issue.

I now have a better understanding of "capturing" with Emmet.  Underlines are our friends.

Thanks!
