### ISSUE TITLE
Can't sync Emmet settings across computers using Git due to new UID key

### ISSUE THREAD

**Issue by michaelalandawson** [emmetio/sublime-text-plugin#77]
I have a Git repository in `~/AppData/Roaming/Sublime Text 3/Packages/User` so that I can sync my ST settings across multiple computers.

This worked fine until the recent update of Emmet.  Now, there is a UID key that contains a value that is different on each of my computers.

I understand from the comments that this is for a future enhancement of Emmet, but what would happen if the UID was the same on multiple computers?

Could this value be added to a different file that could be ignored by Git?

**Comment by rchl** [comment]
If suggest using `sublime.cache_path()`

**Comment by sergeche** [comment]
UID is just a random identifier, which is used to distinct users for tracking Emmet events, if enabled. In future, it will be used for web-based config & cloud sync of preferences. Nothing happens if you use the same UID across multiple instances, unless this UID belongs to a single person. Otherwise, it may sync preferences & snippets if used by multiple users

**Comment by michaelalandawson** [comment]
Thanks for the explanation.

> Nothing happens if you use the same UID across multiple instances, unless this UID belongs to a single person.

It seems like this could be the desired behavior to sync settings across multiple computers if not using Git or other VCS.
